# NVMe perf model config
cmd_overhead=1.7
cmd_overhead_sca=0.7
sca=1
chan_speed=3200
cmd_size=4096
ecc_parity_size=600
page_size=16384
page_parity_size=1952
tR_fast=40
tR=40
tprog_eff=420 #积攒一个b2n,b2n队列无限大，不会空，走sram可以认为这种场景，走ddr会受限于带宽
nand_type=3
tERASE=5000
qd=1024 //gen5: 512, gen6:1024
chan_num=16
die_num=128
plane=4
iwl_slot=512 //Quince/QLTC:256, Aspen/QL-MP:512
read_ratio=100
write_ratio=0
erase_ratio=0
prio_high_ratio=0
prio_normal_ratio=100
prio_low_ratio=0
io_pattern=random
element=32768

//第一阶段随机读，顺序读，顺序写
//分割配置，nand，io pattern，controller

//后端极限能力
//对前端受限条件下的承载能力
//mix场景下的Qos
