# NVMe perf model config
cmd_overhead=1.7
chan_speed=2400
cmd_size=4096
ecc_parity_size=600
tR=40
tPROG=800
tERASE=3000
qd=512
chan_num=16
die_num=128
plane=4
iwl_slot=256
read_ratio=100
write_ratio=0
erase_ratio=0
prio_high_ratio=0
prio_normal_ratio=100
prio_low_ratio=0
element=32768
