# Run legacy random / mixed read-write benchmark cases (Windows PowerShell).
#
# Usage:
#   .\scripts\run_legacy_io_tests.ps1
#   $env:ELEMENT=8192; $env:QD=512; .\scripts\run_legacy_io_tests.ps1

$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$Bin = if ($env:BIN) { $env:BIN } else { Join-Path $Root "nvme_perf_model.exe" }
if (-not (Test-Path $Bin)) {
    $BinNoExt = Join-Path $Root "nvme_perf_model"
    if (Test-Path $BinNoExt) { $Bin = $BinNoExt }
}
$Baseline = if ($env:BASELINE) { $env:BASELINE } else { Join-Path $Root "tests\baseline.conf" }
$OutDir = if ($env:OUT_DIR) { $env:OUT_DIR } else { Join-Path $Root "tests\out" }
$Element = if ($env:ELEMENT) { $env:ELEMENT } else { "16384" }
$Qd = if ($env:QD) { $env:QD } else { "1024" }

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

if (-not (Test-Path $Bin)) {
    Write-Error "Binary not found: $Bin. Run 'make' in $Root first."
}
if (-not (Test-Path $Baseline)) {
    Write-Error "Baseline config not found: $Baseline"
}

function Write-Conf {
    param(
        [string]$OutPath,
        [hashtable]$Overrides
    )
    $lines = Get-Content $Baseline
    $map = @{}
    foreach ($line in $lines) {
        if ($line -match '^\s*#' -or $line -match '^\s*$') { continue }
        $parts = $line -split '=', 2
        if ($parts.Count -eq 2) {
            $map[$parts[0].Trim()] = $parts[1].Trim()
        }
    }
    $map["element"] = $Element
    $map["qd"] = $Qd
    foreach ($key in $Overrides.Keys) {
        $map[$key] = [string]$Overrides[$key]
    }
    $header = @(
        "# Generated by run_legacy_io_tests.ps1",
        "# Case overrides applied on top of tests/baseline.conf"
    )
    $body = foreach ($key in ($map.Keys | Sort-Object)) {
        "$key=$($map[$key])"
    }
    ($header + $body) | Set-Content -Encoding ascii $OutPath
}

function Run-Case {
    param(
        [string]$Name,
        [hashtable]$Overrides
    )
    $conf = Join-Path $OutDir "$Name.conf"
    $log = Join-Path $OutDir "$Name.log"
    Write-Conf -OutPath $conf -Overrides $Overrides
    Write-Host "==> $Name"
    Write-Host "    config: $conf"
    & $Bin $conf 2>&1 | Tee-Object -FilePath $log
    if ($LASTEXITCODE -ne 0) {
        Write-Host "FAIL: $Name (simulator exit $LASTEXITCODE)" -ForegroundColor Red
        return $false
    }
    Write-Host ""
    return $true
}

$Fail = 0

if (-not (Run-Case "rand_read_4k" @{
        read_ratio = 100; write_ratio = 0; block_size = 0; io_pattern = "random"
    })) { $Fail = 1 }

if (-not (Run-Case "rand_write_4k" @{
        read_ratio = 0; write_ratio = 100; block_size = 0; io_pattern = "random"
    })) { $Fail = 1 }

if (-not (Run-Case "mixed_rw_70_30" @{
        read_ratio = 70; write_ratio = 30; block_size = 0; io_pattern = "random"
    })) { $Fail = 1 }

if (-not (Run-Case "mixed_rw_50_50" @{
        read_ratio = 50; write_ratio = 50; block_size = 0; io_pattern = "random"
    })) { $Fail = 1 }

if (-not (Run-Case "rand_read_128k" @{
        read_ratio = 100; write_ratio = 0; block_size = 131072
        io_pattern = "random"; stripe_mode = "channel_major"
    })) { $Fail = 1 }

if (-not (Run-Case "rand_write_128k" @{
        read_ratio = 0; write_ratio = 100; block_size = 131072
        io_pattern = "random"; stripe_mode = "channel_major"
    })) { $Fail = 1 }

if (-not (Run-Case "mixed_rw_70_30_128k" @{
        read_ratio = 70; write_ratio = 30; block_size = 131072
        io_pattern = "random"; stripe_mode = "channel_major"
    })) { $Fail = 1 }

Write-Host "========================================"
if ($Fail -eq 0) {
    Write-Host "All legacy IO tests passed."
    Write-Host "Logs: $OutDir\*.log"
    exit 0
}
Write-Host "Some tests failed. See logs in $OutDir" -ForegroundColor Red
exit 1
